pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') 
    }
    
    stages {
        stage('Checkout') {
            steps {
                // Pull the source code from the repository
                git 'https://github.com/revanthmallampalli/MY-PROJECTS/tree/main/CICD/webappCICD'
            }
        }
        
        stage('Build') {
            steps {
                // Build the application
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                // Run tests
                sh 'npm test'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                // Build the Docker image
                script {
                    def image = docker.build("revanthmallampalli/simple-webapp:${env.BUILD_ID}")
                    image.push()
                }
            }
        }
        
        stage('Deploy') {
            steps {
                // Deploy the application
                sh '''
                docker stop simple-webapp || true
                docker rm simple-webapp || true
                docker run -d -p 3000:3000 --name simple-webapp your-username/simple-webapp:${env.BUILD_ID}
                '''
            }
        }
    }
    
    post {
        always {
            // Clean up after the job is done
            deleteDir()
        }
    }
}

